# Generated by Django 2.2.16 on 2021-05-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comm',
            name='name',
        ),
    ]
